import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author victorg
 */
public class AdditionalTransaction extends javax.swing.JFrame {

    /**
     * Creates new form AdditionalTransaction
     */
    public AdditionalTransaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCompanyNameAdditionalTransaction = new javax.swing.JLabel();
        lblHeadingAdditionalTable = new javax.swing.JLabel();
        lblTransactionType = new javax.swing.JLabel();
        cmboTransactionType = new javax.swing.JComboBox();
        lblTransactionAmount = new javax.swing.JLabel();
        txtTransactionAmountAdditional = new java.awt.TextField();
        lblAdminPasswordAdditional = new javax.swing.JLabel();
        pwAdminUserAdditional = new javax.swing.JPasswordField();
        btnCheckoutAdditionalTransaction = new javax.swing.JButton();
        btnHelpAdditionalTransaction = new javax.swing.JButton();
        btnBackAdditional = new javax.swing.JButton();
        btnCancelAdditional = new javax.swing.JButton();
        lblPasswordAdminAdditional = new javax.swing.JLabel();
        lblTypeValidity = new javax.swing.JLabel();
        lblAmountValidity = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNameAdditionalTransaction.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNameAdditionalTransaction.setText("OBIJENCY FOOD STUFF");

        lblHeadingAdditionalTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHeadingAdditionalTable.setText("ADDITIONAL TRANSACTION");

        lblTransactionType.setText("TRANSCTION TYPE:");

        cmboTransactionType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT AN OPTION", "DEBTOR'S PAYMENT", "DRAWINGS", "ADDITIONAL PAYMENT", "RETURNS" }));
        cmboTransactionType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboTransactionTypeActionPerformed(evt);
            }
        });

        lblTransactionAmount.setText("TRANSACTION AMOUNT:");

        lblAdminPasswordAdditional.setText("ADMIN PASSWORD:");

        pwAdminUserAdditional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwAdminUserAdditionalActionPerformed(evt);
            }
        });

        btnCheckoutAdditionalTransaction.setText("CHECKOUT");
        btnCheckoutAdditionalTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutAdditionalTransactionActionPerformed(evt);
            }
        });

        btnHelpAdditionalTransaction.setText("HELP");
        btnHelpAdditionalTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpAdditionalTransactionActionPerformed(evt);
            }
        });

        btnBackAdditional.setText("BACK ");
        btnBackAdditional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAdditionalActionPerformed(evt);
            }
        });

        btnCancelAdditional.setText("CANCEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBackAdditional, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCompanyNameAdditionalTransaction)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTransactionType)
                                            .addComponent(lblAdminPasswordAdditional))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(lblHeadingAdditionalTable)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmboTransactionType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pwAdminUserAdditional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnCancelAdditional)
                                            .addComponent(lblTransactionAmount, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(26, 26, 26)
                                        .addComponent(txtTransactionAmountAdditional, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAmountValidity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTypeValidity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblPasswordAdminAdditional, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(167, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCheckoutAdditionalTransaction)
                        .addGap(166, 166, 166)
                        .addComponent(btnHelpAdditionalTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCompanyNameAdditionalTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHeadingAdditionalTable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmboTransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTypeValidity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAmountValidity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTransactionAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTransactionAmountAdditional, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdminPasswordAdditional, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwAdminUserAdditional))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPasswordAdminAdditional, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckoutAdditionalTransaction)
                    .addComponent(btnHelpAdditionalTransaction)
                    .addComponent(btnBackAdditional)
                    .addComponent(btnCancelAdditional))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckoutAdditionalTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutAdditionalTransactionActionPerformed
        boolean present1, present2, present3;
        String type = (String) cmboTransactionType.getSelectedItem();
        String totS = txtTransactionAmountAdditional.getText();
        String password = new String(pwAdminUserAdditional.getPassword());
        if(type.equals("SELECT AN OPTION")){
            lblTypeValidity.setForeground(Color.red);
            lblTypeValidity.setText("INVALID");
            present1 = false;
        }
        else{
            present1 = true;
        }
        
        if(totS.trim().isEmpty()) {
            lblAmountValidity.setForeground(Color.red);
            lblAmountValidity.setText("INVALID");
            present2 = false;
        }
        else{
            present2 = true;
        }
        
        if(password.trim().isEmpty()){
            lblPasswordAdminAdditional.setForeground(Color.red);
            lblPasswordAdminAdditional.setText("INVALID");
            present3 = false;
        }
        else{
            present3 = true;
        }
        
        
        
        double tot = Double.parseDouble(txtTransactionAmountAdditional.getText());
        DatabaseConnection dc = new DatabaseConnection();
        boolean match = dc.validateAdminPassword(password);
        if (match == true && present1 == true && present2 == true && present3 
                == true) {
            new Checkout(tot, type).setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "The password you entered does"
                    + "not match any admin user.");
        }
        
    }//GEN-LAST:event_btnCheckoutAdditionalTransactionActionPerformed

    private void btnHelpAdditionalTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpAdditionalTransactionActionPerformed
        HelpAdditionalTransaction at = new HelpAdditionalTransaction();
        at.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHelpAdditionalTransactionActionPerformed

    private void btnBackAdditionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAdditionalActionPerformed
        Transaction at = new Transaction();
        at.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackAdditionalActionPerformed

    private void pwAdminUserAdditionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwAdminUserAdditionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwAdminUserAdditionalActionPerformed

    private void cmboTransactionTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboTransactionTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboTransactionTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdditionalTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdditionalTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdditionalTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdditionalTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdditionalTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackAdditional;
    private javax.swing.JButton btnCancelAdditional;
    private javax.swing.JButton btnCheckoutAdditionalTransaction;
    private javax.swing.JButton btnHelpAdditionalTransaction;
    private javax.swing.JComboBox cmboTransactionType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdminPasswordAdditional;
    private javax.swing.JLabel lblAmountValidity;
    private javax.swing.JLabel lblCompanyNameAdditionalTransaction;
    private javax.swing.JLabel lblHeadingAdditionalTable;
    private javax.swing.JLabel lblPasswordAdminAdditional;
    private javax.swing.JLabel lblTransactionAmount;
    private javax.swing.JLabel lblTransactionType;
    private javax.swing.JLabel lblTypeValidity;
    private javax.swing.JPasswordField pwAdminUserAdditional;
    private java.awt.TextField txtTransactionAmountAdditional;
    // End of variables declaration//GEN-END:variables
}
