import java.sql.ResultSet;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author victorg
 */
public class BackendAccounting extends javax.swing.JFrame {

    /**
     * Creates new form BackendAccounting
     */
    public BackendAccounting() {
        initComponents();
        DatabaseConnection db = new DatabaseConnection();
        ResultSet rs = db.displayBackendAccounting();
        tblBackendAccounting.setModel(DbUtils.resultSetToTableModel(rs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyNameBackendAccounting = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBackendAccounting = new javax.swing.JTable();
        lblBalanceBackendAccounting = new javax.swing.JLabel();
        lblBalanceNumberBackendAccounting = new javax.swing.JLabel();
        lblOverallState = new javax.swing.JLabel();
        btnBackEndAccountingMainMenu = new javax.swing.JButton();
        btnBackendAccountingHelp = new javax.swing.JButton();
        lblDateFrom = new javax.swing.JLabel();
        lblDateTo = new javax.swing.JLabel();
        dcDateFromBackendAccounting = new com.toedter.calendar.JDateChooser();
        dcDateToBackendAccounting = new com.toedter.calendar.JDateChooser();
        btnDisplayScreen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNameBackendAccounting.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNameBackendAccounting.setText("OBIJENCY FOOD STUFF");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BACKEND ACCOUNTING TABLE");

        tblBackendAccounting.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PRODUCT ID", "DATE", "COST- PRICE", "SALES - PRICE", "NUMBER SOLD", "TOTAL PROFIT"
            }
        ));
        jScrollPane1.setViewportView(tblBackendAccounting);

        lblBalanceBackendAccounting.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBalanceBackendAccounting.setText("BALANCE:");

        lblBalanceNumberBackendAccounting.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblOverallState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnBackEndAccountingMainMenu.setText("MAIN MENU");
        btnBackEndAccountingMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackEndAccountingMainMenuActionPerformed(evt);
            }
        });

        btnBackendAccountingHelp.setText("HELP");
        btnBackendAccountingHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackendAccountingHelpActionPerformed(evt);
            }
        });

        lblDateFrom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDateFrom.setText("DATE FROM:");

        lblDateTo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDateTo.setText("DATE TO:");

        btnDisplayScreen.setText("DISPLAY");
        btnDisplayScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayScreenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(lblCompanyNameBackendAccounting))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBackEndAccountingMainMenu)
                                        .addGap(115, 115, 115)
                                        .addComponent(lblDateTo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOverallState, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77)
                                        .addComponent(lblDateFrom)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dcDateFromBackendAccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcDateToBackendAccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblBalanceBackendAccounting)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblBalanceNumberBackendAccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnDisplayScreen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBackendAccountingHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCompanyNameBackendAccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBackEndAccountingMainMenu)
                            .addComponent(btnBackendAccountingHelp)
                            .addComponent(lblDateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDisplayScreen))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOverallState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBalanceNumberBackendAccounting, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBalanceBackendAccounting, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(dcDateFromBackendAccounting, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(dcDateToBackendAccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackendAccountingHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackendAccountingHelpActionPerformed
        HelpBackendAccounting ba = new HelpBackendAccounting();
        ba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackendAccountingHelpActionPerformed

    private void btnBackEndAccountingMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackEndAccountingMainMenuActionPerformed
        MainMenu ba = new MainMenu();
        ba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackEndAccountingMainMenuActionPerformed

    private void btnDisplayScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayScreenActionPerformed
        String date1 = ((JTextField)dcDateFromBackendAccounting.getDateEditor().getUiComponent()).getText();
        String date2 = ((JTextField)dcDateToBackendAccounting.getDateEditor().getUiComponent()).getText();
        String day1 = date1.substring(0, 2);
        String month1 = date1.substring(3, 6);
        String year1 = date1.substring(7, 11);
        
        String day2 = date2.substring(0, 2);
        String month2 = date2.substring(3, 6);
        String year2 = date2.substring(7, 11);
        switch(month1) {
            case "Jan":
                month1 = "01";
            break;

            case "Feb":
                month1 = "02";
            break;
                
            case "Mar":
                month1 = "03";
            break;

            case "Apr":
                month1 = "04";
            break;

            case "May":
                month1 = "05";
            break;

            case "Jun":
                month1 = "06";
            break;
        
            case "Jul":
                month1 = "07";
            break;
                
            case "Aug":
                month1 = "08";
            break;

            case "Sep":
                month1 = "09";
            break;

            case "Oct":
                month1 = "10";
            break;

            case "Nov":
                month1 = "11";
            break;
                
            case "Dec":
                month1 = "12";
            break;
                
            default:
                System.out.println("It is not a month");
            break;
            }
        
        String dates1 = year1 + month1 + day1 + "_000000";
        
        switch(month2) {
            case "Jan":
                month2 = "01";
            break;

            case "Feb":
                month2 = "02";
            break;
                
            case "Mar":
                month2 = "03";
            break;

            case "Apr":
                month2 = "04";
            break;

            case "May":
                month2 = "05";
            break;

            case "Jun":
                month2 = "06";
            break;
        
            case "Jul":
                month2 = "07";
            break;
                
            case "Aug":
                month2 = "08";
            break;

            case "Sep":
                month2 = "09";
            break;

            case "Oct":
                month2 = "10";
            break;

            case "Nov":
                month2 = "11";
            break;
                
            case "Dec":
                month2 = "12";
            break;
                
            default:
                System.out.println("It is not a month");
            break;
            }
        
        String dates2 = year2 + month2 + day2 + "_000000";
        
        DatabaseConnection dc = new DatabaseConnection();
        ResultSet rs = dc.displayBasedOnDateBackend(dates1, dates2);
        tblBackendAccounting.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnDisplayScreenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackendAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackendAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackendAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackendAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackendAccounting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackEndAccountingMainMenu;
    private javax.swing.JButton btnBackendAccountingHelp;
    private javax.swing.JButton btnDisplayScreen;
    private com.toedter.calendar.JDateChooser dcDateFromBackendAccounting;
    private com.toedter.calendar.JDateChooser dcDateToBackendAccounting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalanceBackendAccounting;
    private javax.swing.JLabel lblBalanceNumberBackendAccounting;
    private javax.swing.JLabel lblCompanyNameBackendAccounting;
    private javax.swing.JLabel lblDateFrom;
    private javax.swing.JLabel lblDateTo;
    private javax.swing.JLabel lblOverallState;
    private javax.swing.JTable tblBackendAccounting;
    // End of variables declaration//GEN-END:variables
}
