import javax.swing.*;

/**
 *
 * @author victorg
 */
public class Checkout extends javax.swing.JFrame {

    /**
     * Creates new form Checkout
     */
    public Checkout() {
        initComponents();
        
    }
    private double tot;
    private String t;
    public Checkout(double totAmount, String type) {
        initComponents();
        tot = totAmount;
        t = type;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyNameCheckout = new javax.swing.JLabel();
        lblBalanceCheckout = new javax.swing.JLabel();
        lblBalanceNumberCheckout = new javax.swing.JLabel();
        lblAmountGiven = new javax.swing.JLabel();
        txtAmountGiven = new javax.swing.JTextField();
        btnCheckout = new javax.swing.JButton();
        lblDebtorOrNot = new javax.swing.JLabel();
        cmboDebtorOrNot = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNameCheckout.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNameCheckout.setText("OBIJENCY FOOD STUFF");

        lblBalanceCheckout.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblBalanceCheckout.setText("Balance:");

        lblBalanceNumberCheckout.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lblAmountGiven.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAmountGiven.setText("AMOUNT GIVEN:");

        txtAmountGiven.setText("R");
        txtAmountGiven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountGivenActionPerformed(evt);
            }
        });

        btnCheckout.setText("CHECKOUT");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        lblDebtorOrNot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDebtorOrNot.setText("IS IT A DEBTOR OR NOT:");

        cmboDebtorOrNot.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT YES OR NO", "NO ", "YES" }));

        btnBack.setText("MAIN MENU");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBalanceCheckout)
                                    .addComponent(lblAmountGiven))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBalanceNumberCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(txtAmountGiven, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(lblDebtorOrNot)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCheckout)
                                    .addComponent(cmboDebtorOrNot, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lblCompanyNameCheckout))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCompanyNameCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblBalanceCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblBalanceNumberCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmountGiven, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountGiven, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDebtorOrNot, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmboDebtorOrNot)
                        .addGap(3, 3, 3)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnCheckout))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountGivenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountGivenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountGivenActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        DatabaseConnection db = new DatabaseConnection();
        String text = txtAmountGiven.getText();
        String ag = text.substring(text.indexOf("R")+1, text.length());
        double amount = Double.parseDouble(ag);
        String bal = "" + tot;
        lblBalanceNumberCheckout.setText(bal);
        double balance = tot;
        double change = amount-balance;
        String type = (String) cmboDebtorOrNot.getSelectedItem();
        if (type.equals("YES")) {
            type = t + "(Debtor)";
        }
        else
            if (type.equals("NO")) {
             type = t;
        }
        
        db.addTransaction(amount, balance, type);
        
        if(type.equals(t + "(Debtor)")){
        JOptionPane.showInputDialog(this,"Transaction is complete.\n"
                + "Amount:\tR" + balance + "\nThis is a debtor transaction please"
                + "create a debtor transaction.");
        }
        else
            if(type.equals(t)){
                JOptionPane.showInputDialog(null,"Transaction is complete.\n"
                + "Amount:\tR" + balance + "\nChange: " + change +
                "\nThis is a operational transaction you can proceed to the main menu.");
            }
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JComboBox cmboDebtorOrNot;
    private javax.swing.JLabel lblAmountGiven;
    private javax.swing.JLabel lblBalanceCheckout;
    private javax.swing.JLabel lblBalanceNumberCheckout;
    private javax.swing.JLabel lblCompanyNameCheckout;
    private javax.swing.JLabel lblDebtorOrNot;
    private javax.swing.JTextField txtAmountGiven;
    // End of variables declaration//GEN-END:variables
}
