import java.sql.ResultSet;
import java.util.Locale;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author victorg
 */
public class LoginTable extends javax.swing.JFrame {

    /**
     * Creates new form LoginTable
     */
    public LoginTable() {
        initComponents();
        DatabaseConnection db = new DatabaseConnection();
        ResultSet rs = db.displayLoginTable();
        tblLoginTable.setModel(DbUtils.resultSetToTableModel(rs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyNameLoginTable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoginTable = new javax.swing.JTable();
        btnLoginMainMenu = new javax.swing.JButton();
        btnLoginHelp = new javax.swing.JButton();
        lblDateToLogintable = new javax.swing.JLabel();
        lblDateFromLoginTable = new javax.swing.JLabel();
        dcDateFromLoginTable = new com.toedter.calendar.JDateChooser();
        dcDateToLoginTable = new com.toedter.calendar.JDateChooser();
        btnDisplayLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNameLoginTable.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNameLoginTable.setText("OBIJENCY FOOD STUFF");

        tblLoginTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "LOGIN ID", "STATUS", "LOGIN TIME", "USER ID"
            }
        ));
        jScrollPane1.setViewportView(tblLoginTable);

        btnLoginMainMenu.setText("MAIN MENU");
        btnLoginMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginMainMenuActionPerformed(evt);
            }
        });

        btnLoginHelp.setText("HELP");
        btnLoginHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginHelpActionPerformed(evt);
            }
        });

        lblDateToLogintable.setText("DATE TO:");

        lblDateFromLoginTable.setText("DATE FROM:");

        btnDisplayLogin.setText("DISPLAY");
        btnDisplayLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lblCompanyNameLoginTable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoginMainMenu)
                        .addGap(27, 27, 27)
                        .addComponent(btnDisplayLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDateFromLoginTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDateToLogintable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcDateFromLoginTable, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(dcDateToLoginTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoginHelp)))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCompanyNameLoginTable, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLoginHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnLoginMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDateFromLoginTable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcDateFromLoginTable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDateToLogintable, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(dcDateToLoginTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginMainMenuActionPerformed
        MainMenu lt = new MainMenu();
        lt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginMainMenuActionPerformed

    private void btnLoginHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginHelpActionPerformed
        HelpLoginTable lt = new HelpLoginTable();
        lt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginHelpActionPerformed

    private void btnDisplayLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayLoginActionPerformed
        String date1 = ((JTextField)dcDateFromLoginTable.getDateEditor().getUiComponent()).getText();
        String date2 = ((JTextField)dcDateToLoginTable.getDateEditor().getUiComponent()).getText();
        String day1 = date1.substring(0, 2);
        String month1 = date1.substring(3, 6);
        String year1 = date1.substring(7, 11);
        
        String day2 = date2.substring(0, 2);
        String month2 = date2.substring(3, 6);
        String year2 = date2.substring(7, 11);
        switch(month1) {
            case "Jan":
                month1 = "01";
            break;

            case "Feb":
                month1 = "02";
            break;
                
            case "Mar":
                month1 = "03";
            break;

            case "Apr":
                month1 = "04";
            break;

            case "May":
                month1 = "05";
            break;

            case "Jun":
                month1 = "06";
            break;
        
            case "Jul":
                month1 = "07";
            break;
                
            case "Aug":
                month1 = "08";
            break;

            case "Sep":
                month1 = "09";
            break;

            case "Oct":
                month1 = "10";
            break;

            case "Nov":
                month1 = "11";
            break;
                
            case "Dec":
                month1 = "12";
            break;
                
            default:
                System.out.println("It is not a month");
            break;
            }
        
        String dates1 = year1 + month1 + day1 + "_000000";
        
        switch(month2) {
            case "Jan":
                month2 = "01";
            break;

            case "Feb":
                month2 = "02";
            break;
                
            case "Mar":
                month2 = "03";
            break;

            case "Apr":
                month2 = "04";
            break;

            case "May":
                month2 = "05";
            break;

            case "Jun":
                month2 = "06";
            break;
        
            case "Jul":
                month2 = "07";
            break;
                
            case "Aug":
                month2 = "08";
            break;

            case "Sep":
                month2 = "09";
            break;

            case "Oct":
                month2 = "10";
            break;

            case "Nov":
                month2 = "11";
            break;
                
            case "Dec":
                month2 = "12";
            break;
                
            default:
                System.out.println("It is not a month");
            break;
            }
        
        String dates2 = year2 + month2 + day2 + "_000000";
        
        DatabaseConnection dc = new DatabaseConnection();
        ResultSet rs = dc.displayBasedOnDateLogin(dates1, dates2);
        tblLoginTable.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnDisplayLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplayLogin;
    private javax.swing.JButton btnLoginHelp;
    private javax.swing.JButton btnLoginMainMenu;
    private com.toedter.calendar.JDateChooser dcDateFromLoginTable;
    private com.toedter.calendar.JDateChooser dcDateToLoginTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompanyNameLoginTable;
    private javax.swing.JLabel lblDateFromLoginTable;
    private javax.swing.JLabel lblDateToLogintable;
    private javax.swing.JTable tblLoginTable;
    // End of variables declaration//GEN-END:variables
}
