import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author victorg
 */
public class MainMenu extends javax.swing.JFrame {

   
    
    public MainMenu() {
        initComponents();
        DatabaseConnection db = new DatabaseConnection();
        ResultSet rs = db.TransactionsForDay();
        tblTransactionHistory.setModel(DbUtils.resultSetToTableModel(rs));
        String bal = db.getBalanceForDay();
        lblBalNumberMainMenu.setText(bal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblCompanyNameMainMenu = new javax.swing.JLabel();
        btnTransactionHistoryMainMenu = new javax.swing.JButton();
        btnStockMainMenu = new javax.swing.JButton();
        btnPriceListmainMenu = new javax.swing.JButton();
        btnDebtorsMainMenu = new javax.swing.JButton();
        btnBackendAccountingMainMenu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTransactionHistory = new javax.swing.JTable();
        lblUserProfileMainMenu = new javax.swing.JLabel();
        btnSettingsMainMenu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblHeadingMainMenu = new javax.swing.JLabel();
        lblBalMainMenu = new javax.swing.JLabel();
        lblBalNumberMainMenu = new javax.swing.JLabel();
        btnNewTransaction = new javax.swing.JButton();
        btnMainMenuHelp = new javax.swing.JButton();
        btnLoginTable = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNameMainMenu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNameMainMenu.setText("OBIJENCY FOOD STUFF");

        btnTransactionHistoryMainMenu.setText("TRANSACTION HISTORY");
        btnTransactionHistoryMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionHistoryMainMenuActionPerformed(evt);
            }
        });

        btnStockMainMenu.setText("STOCK ");
        btnStockMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockMainMenuActionPerformed(evt);
            }
        });

        btnPriceListmainMenu.setText("PRICE LIST");
        btnPriceListmainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceListmainMenuActionPerformed(evt);
            }
        });

        btnDebtorsMainMenu.setText("DEBTORS");
        btnDebtorsMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDebtorsMainMenuActionPerformed(evt);
            }
        });

        btnBackendAccountingMainMenu.setText("BACKEND ACCOUNTING");
        btnBackendAccountingMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackendAccountingMainMenuActionPerformed(evt);
            }
        });

        tblTransactionHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Timestamp", "Total Amount", "Amount Given", "Type "
            }
        ));
        jScrollPane3.setViewportView(tblTransactionHistory);

        btnSettingsMainMenu.setText("SETTINGS");
        btnSettingsMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsMainMenuActionPerformed(evt);
            }
        });

        jButton1.setText("USERS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblHeadingMainMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHeadingMainMenu.setText("TRANSACTIONS");

        lblBalMainMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBalMainMenu.setText("BAL:");

        btnNewTransaction.setText("NEW TRANSACTION");
        btnNewTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTransactionActionPerformed(evt);
            }
        });

        btnMainMenuHelp.setText("HELP");
        btnMainMenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuHelpActionPerformed(evt);
            }
        });

        btnLoginTable.setText("LOGIN TABLE");
        btnLoginTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginTableActionPerformed(evt);
            }
        });

        btnSignOut.setText("SIGN OUT");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPriceListmainMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransactionHistoryMainMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStockMainMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDebtorsMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBackendAccountingMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewTransaction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHeadingMainMenu)
                                .addGap(326, 326, 326))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblBalMainMenu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBalNumberMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(lblCompanyNameMainMenu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMainMenuHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(lblUserProfileMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSettingsMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLoginTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCompanyNameMainMenu)
                            .addComponent(lblUserProfileMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSettingsMainMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLoginTable))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblHeadingMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTransactionHistoryMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStockMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPriceListmainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDebtorsMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBackendAccountingMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBalNumberMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMainMenuHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 102, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransactionHistoryMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionHistoryMainMenuActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        boolean match = dc.getUserType();
        if(match == true){
        TransactionHistory mm = new TransactionHistory();
        mm.setVisible(true);
        this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "You cannot access this page as"
                    + " you're not an admin user");
        }
    }//GEN-LAST:event_btnTransactionHistoryMainMenuActionPerformed

    private void btnStockMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockMainMenuActionPerformed
        StockManagement mm = new StockManagement();
        mm.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnStockMainMenuActionPerformed

    private void btnPriceListmainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceListmainMenuActionPerformed
        PriceList mm = new PriceList();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPriceListmainMenuActionPerformed

    private void btnDebtorsMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDebtorsMainMenuActionPerformed
        Debtors mm = new Debtors();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDebtorsMainMenuActionPerformed

    private void btnBackendAccountingMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackendAccountingMainMenuActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        boolean match = dc.getUserType();
        if(match == true){
        BackendAccounting mm = new BackendAccounting();
        mm.setVisible(true);
        this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "You cannot access this page as"
                    + " you're not an admin user");
        }
    }//GEN-LAST:event_btnBackendAccountingMainMenuActionPerformed

    private void btnSettingsMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsMainMenuActionPerformed
        Settings mm = new Settings();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSettingsMainMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        boolean match = dc.getUserType();
        if(match == true){
        UsersTable mm = new UsersTable();
        mm.setVisible(true);
        this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "You cannot access this page as"
                    + " you're not an admin user");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLoginTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginTableActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        boolean match = dc.getUserType();
        if(match == true){
        LoginTable mm = new LoginTable();
        mm.setVisible(true);
        this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "You cannot access this page as"
                    + " you're not an admin user");
        }
    }//GEN-LAST:event_btnLoginTableActionPerformed

    private void btnNewTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTransactionActionPerformed
        Transaction mm = new Transaction();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNewTransactionActionPerformed

    private void btnMainMenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuHelpActionPerformed
        HelpMainMenu mm = new HelpMainMenu();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMainMenuHelpActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        SignIn mm = new SignIn();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackendAccountingMainMenu;
    private javax.swing.JButton btnDebtorsMainMenu;
    private javax.swing.JButton btnLoginTable;
    private javax.swing.JButton btnMainMenuHelp;
    private javax.swing.JButton btnNewTransaction;
    private javax.swing.JButton btnPriceListmainMenu;
    private javax.swing.JButton btnSettingsMainMenu;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnStockMainMenu;
    private javax.swing.JButton btnTransactionHistoryMainMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBalMainMenu;
    private javax.swing.JLabel lblBalNumberMainMenu;
    private javax.swing.JLabel lblCompanyNameMainMenu;
    private javax.swing.JLabel lblHeadingMainMenu;
    private javax.swing.JLabel lblUserProfileMainMenu;
    private javax.swing.JTable tblTransactionHistory;
    // End of variables declaration//GEN-END:variables
}
