
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victorg
 */
public class ManualTransaction extends javax.swing.JFrame {

    /**
     * Creates new form ManualTransaction
     */
    public ManualTransaction() {
        initComponents();
    }
    
    private String product;
    private int qty;
    public ManualTransaction(String pr){
        initComponents();
        product = pr;
        String p = product;
        System.out.println(product);
        DatabaseConnection dc = new DatabaseConnection();
        String price = dc.getPriceFromProduct(p);
        qty = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter the quantity"));
        writeToFile(product, price, qty);
        readFile();
    }
    
    

    private void writeToFile(String p, String pr, int qty){
        try {
            PrintWriter outFile = new PrintWriter(new FileWriter("TempFile.txt", true));
            String line = p + "," + pr + "," + qty;
            outFile.println(line);
            outFile.close();
        } catch (IOException e) {
        }
    }
    
    private void readFile(){
        
        try {
            DefaultTableModel model = (DefaultTableModel)tblManual.getModel();
            Scanner sc = new Scanner(new File("TempFile.txt"));
            while(sc.hasNextLine()){
                String line = sc.nextLine();
                String[] row = line.split(",");
                model.addRow(row);
            }
            sc.close();
        } catch (FileNotFoundException e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyNameManual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManual = new javax.swing.JTable();
        btnManualCheckout = new javax.swing.JButton();
        btnManualTransaction = new javax.swing.JButton();
        btnManualHelp = new javax.swing.JButton();
        btnAddTransaction = new javax.swing.JButton();
        btnManualCancel = new javax.swing.JButton();
        btnRemoveItemManual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNameManual.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNameManual.setText("OBIJENCY FOOD STUFF");

        tblManual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ITEM", "PRICE", "Number"
            }
        ));
        jScrollPane1.setViewportView(tblManual);

        btnManualCheckout.setText("CHECKOUT");
        btnManualCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualCheckoutActionPerformed(evt);
            }
        });

        btnManualTransaction.setText("BACK");
        btnManualTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualTransactionActionPerformed(evt);
            }
        });

        btnManualHelp.setText("HELP");
        btnManualHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualHelpActionPerformed(evt);
            }
        });

        btnAddTransaction.setText("ADD ITEM");
        btnAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTransactionActionPerformed(evt);
            }
        });

        btnManualCancel.setText("CANCEL");
        btnManualCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualCancelActionPerformed(evt);
            }
        });

        btnRemoveItemManual.setText("REMOVE ITEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnManualTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btnManualCancel)
                .addGap(104, 104, 104)
                .addComponent(btnManualCheckout)
                .addGap(148, 148, 148)
                .addComponent(btnManualHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCompanyNameManual, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRemoveItemManual)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCompanyNameManual, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTransaction)
                    .addComponent(btnRemoveItemManual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManualTransaction)
                    .addComponent(btnManualHelp)
                    .addComponent(btnManualCancel)
                    .addComponent(btnManualCheckout))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManualCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualCheckoutActionPerformed

        Checkout mt = new Checkout();
        mt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManualCheckoutActionPerformed

    private void btnManualCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualCancelActionPerformed
        MainMenu mt = new MainMenu();
        mt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManualCancelActionPerformed

    private void btnManualHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualHelpActionPerformed
        HelpManualTransaction mt = new HelpManualTransaction();
        mt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManualHelpActionPerformed

    private void btnManualTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualTransactionActionPerformed
        Transaction mt = new Transaction();
        mt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManualTransactionActionPerformed

    private void btnAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTransactionActionPerformed
        
        SearchProduct sp = new SearchProduct();
        sp.setVisible(true);
        
    }//GEN-LAST:event_btnAddTransactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManualTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManualTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManualTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManualTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManualTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTransaction;
    private javax.swing.JButton btnManualCancel;
    private javax.swing.JButton btnManualCheckout;
    private javax.swing.JButton btnManualHelp;
    private javax.swing.JButton btnManualTransaction;
    private javax.swing.JButton btnRemoveItemManual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompanyNameManual;
    private javax.swing.JTable tblManual;
    // End of variables declaration//GEN-END:variables
}
