
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author victorg
 */
public class PriceList extends javax.swing.JFrame {

    /**
     * Creates new form PriceList
     */
    public PriceList() {
        initComponents();
        
        DatabaseConnection db = new DatabaseConnection();
        ResultSet rs = db.displayPriceList();
        tblPriceList.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyNamePriceList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPriceList = new javax.swing.JTable();
        btnPriceListMainMenu = new javax.swing.JButton();
        btnPriceListHelp = new javax.swing.JButton();
        btnPriceDESC = new javax.swing.JButton();
        btnPriceASC = new javax.swing.JButton();
        btnEditPrice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNamePriceList.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNamePriceList.setText("OBIJENCY FOOD STUFF");

        tblPriceList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PRICE ID", "PRODUCT ID", "COSTPRICE", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(tblPriceList);

        btnPriceListMainMenu.setText("MAIN MENU");
        btnPriceListMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceListMainMenuActionPerformed(evt);
            }
        });

        btnPriceListHelp.setText("HELP");
        btnPriceListHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceListHelpActionPerformed(evt);
            }
        });

        btnPriceDESC.setText("PRICE DESCENDING");
        btnPriceDESC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceDESCActionPerformed(evt);
            }
        });

        btnPriceASC.setText("PRICE ASCENDING");
        btnPriceASC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceASCActionPerformed(evt);
            }
        });

        btnEditPrice.setText("EDIT PRICE");
        btnEditPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnPriceListMainMenu)
                .addGap(74, 74, 74)
                .addComponent(btnPriceDESC)
                .addGap(80, 80, 80)
                .addComponent(btnPriceASC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnPriceListHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblCompanyNamePriceList, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btnEditPrice)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCompanyNamePriceList, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnEditPrice)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPriceListMainMenu)
                    .addComponent(btnPriceListHelp)
                    .addComponent(btnPriceDESC)
                    .addComponent(btnPriceASC))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPriceListHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceListHelpActionPerformed
        HelpPriceList pl = new HelpPriceList();
        pl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPriceListHelpActionPerformed

    private void btnPriceListMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceListMainMenuActionPerformed
        MainMenu hpl = new MainMenu();
        hpl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPriceListMainMenuActionPerformed

    private void btnEditPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPriceActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        int prID = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter the price ID of the product"));
        String[] choices = {"CostPrice", "Price"};
        int x = JOptionPane.showOptionDialog(this, "Please select the details that you want to change.",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, choices, choices[0]);
        String choice = choices[x];
        double amount = Double.parseDouble(JOptionPane.showInputDialog(this, "Please enter the new value for the " + choice
        + " of the product"));
        int row = dc.editPrice(prID, choice, amount);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "The " + choice + " has been updated");
        }
        else{
            JOptionPane.showMessageDialog(this, "The " + choice + " has been updated");
        }
    }//GEN-LAST:event_btnEditPriceActionPerformed

    private void btnPriceDESCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceDESCActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        ResultSet rs = dc.PriceDesc();
        tblPriceList.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnPriceDESCActionPerformed

    private void btnPriceASCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceASCActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        ResultSet rs = dc.PriceAsc();
        tblPriceList.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnPriceASCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PriceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PriceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PriceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PriceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PriceList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditPrice;
    private javax.swing.JButton btnPriceASC;
    private javax.swing.JButton btnPriceDESC;
    private javax.swing.JButton btnPriceListHelp;
    private javax.swing.JButton btnPriceListMainMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompanyNamePriceList;
    private javax.swing.JTable tblPriceList;
    // End of variables declaration//GEN-END:variables
}
