import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author victorg
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        
        DatabaseConnection db = new DatabaseConnection();
        String result = db.applySettings();
        Scanner sc = new Scanner(result).useDelimiter(",");
        String name = sc.next();
        String surname = sc.next();
        String username = sc.next();
        String password = sc.next();
        String status = sc.next();
        sc.close();
        lblDisplayNameSettings.setText(name);
        lblDisplaySurnameSettings.setText(surname);
        lblDisplayUsernameSettings.setText(username);
        pwfPasswordUser.setText(password);
        lblDisplayStatusSettings.setText(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyNameSettings = new javax.swing.JLabel();
        lblNameSettings = new javax.swing.JLabel();
        lblSurnameSettings = new javax.swing.JLabel();
        lblPasswordSettings = new javax.swing.JLabel();
        lblStatusSettings = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblUsernameSettings = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnChangeUsername = new javax.swing.JButton();
        btnChangeSurname = new javax.swing.JButton();
        btnChangeName = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnSaveSettings = new javax.swing.JButton();
        btnSettingsMainMenu = new javax.swing.JButton();
        btnHelpSettings = new javax.swing.JButton();
        lblDisplayNameSettings = new javax.swing.JLabel();
        lblDisplaySurnameSettings = new javax.swing.JLabel();
        lblDisplayUsernameSettings = new javax.swing.JLabel();
        pwfPasswordUser = new javax.swing.JPasswordField();
        lblDisplayStatusSettings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNameSettings.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNameSettings.setText("OBIJENCY FOOD STUFF");

        lblNameSettings.setText("NAME:");

        lblSurnameSettings.setText("SURNAME:");

        lblPasswordSettings.setText("PASSWORD:");

        lblStatusSettings.setText("STATUS:");

        lblUsernameSettings.setText("USERNAME:");

        btnChangeUsername.setText("CHANGE");
        btnChangeUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeUsernameActionPerformed(evt);
            }
        });

        btnChangeSurname.setText("CHANGE");
        btnChangeSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeSurnameActionPerformed(evt);
            }
        });

        btnChangeName.setText("CHANGE");
        btnChangeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeNameActionPerformed(evt);
            }
        });

        btnChangePassword.setText("CHANGE");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnSaveSettings.setText("SAVE");
        btnSaveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSettingsActionPerformed(evt);
            }
        });

        btnSettingsMainMenu.setText("MAIN MENU");
        btnSettingsMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsMainMenuActionPerformed(evt);
            }
        });

        btnHelpSettings.setText("HELP");
        btnHelpSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpSettingsActionPerformed(evt);
            }
        });

        pwfPasswordUser.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCompanyNameSettings)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSettingsMainMenu)
                                .addGap(90, 90, 90)
                                .addComponent(btnSaveSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblPasswordSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUsernameSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblStatusSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblSurnameSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                        .addComponent(lblNameSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDisplayNameSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDisplaySurnameSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDisplayUsernameSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pwfPasswordUser, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(lblDisplayStatusSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnChangeUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangeSurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangeName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHelpSettings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCompanyNameSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDisplayNameSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangeName)
                    .addComponent(lblNameSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDisplaySurnameSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangeSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSurnameSettings))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisplayUsernameSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChangeUsername)
                            .addComponent(lblUsernameSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPasswordSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePassword)
                    .addComponent(pwfPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblStatusSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDisplayStatusSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveSettings)
                    .addComponent(btnSettingsMainMenu)
                    .addComponent(btnHelpSettings))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeUsernameActionPerformed
        String newUsername = JOptionPane.showInputDialog(this, "Enter the "
                + " new username you want");
        DatabaseConnection dc = new DatabaseConnection();
        boolean state = dc.validateUsername(newUsername);
        while(state == true){
            if(state == true){
            newUsername = JOptionPane.showInputDialog(this, "Please try again by entering a new username.");
            state = dc.validateSignUpName(newUsername);
            }
        }
        lblDisplayUsernameSettings.setText(newUsername);
    }//GEN-LAST:event_btnChangeUsernameActionPerformed

    private void btnSettingsMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsMainMenuActionPerformed
        MainMenu s = new MainMenu();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSettingsMainMenuActionPerformed

    private void btnHelpSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpSettingsActionPerformed
        HelpSettings sp = new HelpSettings();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHelpSettingsActionPerformed

    private void btnChangeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeNameActionPerformed
        String newName = JOptionPane.showInputDialog(this, "Enter the new name you want to input.");
        DatabaseConnection dc = new DatabaseConnection();
        boolean state = dc.validateSignUpName(newName);
        while(state == true){
            if(state == true){
            newName = JOptionPane.showInputDialog(this, "Please try again by entering a new name.");
            state = dc.validateSignUpName(newName);
            }
        }
        lblDisplayNameSettings.setText(newName);
        
    }//GEN-LAST:event_btnChangeNameActionPerformed

    private void btnChangeSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeSurnameActionPerformed
        String newSurname = JOptionPane.showInputDialog(this, "Enter the new"
                + " surname you want to input.");
        DatabaseConnection dc = new DatabaseConnection();
        boolean state = dc.validateSignUpSurname(newSurname);
        while(state == true){
            if(state == true){
            newSurname = JOptionPane.showInputDialog(this, "Please try again by entering a new surname.");
            state = dc.validateSignUpName(newSurname);
            }
        }
        lblDisplaySurnameSettings.setText(newSurname);
    }//GEN-LAST:event_btnChangeSurnameActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        String newPassword = JOptionPane.showInputDialog(this, "Enter the new "
                + "password you want");
        pwfPasswordUser.setText(newPassword);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnSaveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSettingsActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        String password = new String(pwfPasswordUser.getPassword());
        int row = dc.saveSettings(lblDisplayNameSettings.getText(), 
                lblDisplaySurnameSettings.getText(), lblDisplayUsernameSettings.getText(), 
                password);
        if(row > 0){
            JOptionPane.showMessageDialog(this, "Your settings have been saved.");
        }
        else{
            JOptionPane.showMessageDialog(this, "Your settings have not been saved.");
        }
    }//GEN-LAST:event_btnSaveSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeName;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangeSurname;
    private javax.swing.JButton btnChangeUsername;
    private javax.swing.JButton btnHelpSettings;
    private javax.swing.JButton btnSaveSettings;
    private javax.swing.JButton btnSettingsMainMenu;
    private javax.swing.JLabel lblCompanyNameSettings;
    private javax.swing.JLabel lblDisplayNameSettings;
    private javax.swing.JLabel lblDisplayStatusSettings;
    private javax.swing.JLabel lblDisplaySurnameSettings;
    private javax.swing.JLabel lblDisplayUsernameSettings;
    private javax.swing.JLabel lblNameSettings;
    private javax.swing.JLabel lblPasswordSettings;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusSettings;
    private javax.swing.JLabel lblSurnameSettings;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsernameSettings;
    private javax.swing.JPasswordField pwfPasswordUser;
    // End of variables declaration//GEN-END:variables
}
