import java.awt.Color;
import javax.swing.*;
/**
 *
 * @author victorg
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyNameSignIn = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPasswordSignIn = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        txtUsernameSignIn = new java.awt.TextField();
        btnHelpSignIn = new javax.swing.JButton();
        btnCancelSignIn = new javax.swing.JButton();
        pwfPasswordSignIn = new javax.swing.JPasswordField();
        btnSignUpSignIn = new javax.swing.JButton();
        lblUsernameValidity = new javax.swing.JLabel();
        lblPasswordValidity = new javax.swing.JLabel();
        lblUserType = new javax.swing.JLabel();
        cmboUserType = new javax.swing.JComboBox();
        lblUserValidity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNameSignIn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNameSignIn.setText("OBIJENCY FOOD STUFF");

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername.setText("USERNAME:");

        lblPasswordSignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPasswordSignIn.setText("PASSWORD:");

        btnSignIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSignIn.setText("SIGN IN");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        txtUsernameSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameSignInMouseClicked(evt);
            }
        });
        txtUsernameSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameSignInActionPerformed(evt);
            }
        });

        btnHelpSignIn.setText("HELP");
        btnHelpSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpSignInActionPerformed(evt);
            }
        });

        btnCancelSignIn.setText("CANCEL");
        btnCancelSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSignInActionPerformed(evt);
            }
        });

        pwfPasswordSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwfPasswordSignInMouseClicked(evt);
            }
        });
        pwfPasswordSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwfPasswordSignInActionPerformed(evt);
            }
        });

        btnSignUpSignIn.setText("SIGN UP");
        btnSignUpSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpSignInActionPerformed(evt);
            }
        });

        lblUserType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserType.setText("USER TYPE:");

        cmboUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMIN ", "EMPLOYEE" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblCompanyNameSignIn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelSignIn)
                                .addGap(115, 115, 115)
                                .addComponent(btnSignUpSignIn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPasswordSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pwfPasswordSignIn)
                                    .addComponent(txtUsernameSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(cmboUserType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsernameValidity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHelpSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPasswordValidity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserValidity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCompanyNameSignIn)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblUsernameValidity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsernameSignIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPasswordSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pwfPasswordSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblPasswordValidity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(cmboUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblUserValidity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUpSignIn)
                    .addComponent(btnHelpSignIn)
                    .addComponent(btnCancelSignIn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        DatabaseConnection db = new DatabaseConnection();
        
        String user = txtUsernameSignIn.getText();
        String password = new String(pwfPasswordSignIn.getPassword());
        String userType = (String) cmboUserType.getSelectedItem();
        userType = userType.toLowerCase();
        db.setUsername(user);
        db.setPassword(password);
        Boolean match = db.validateSignIn(user, password, userType);
        if(match == true){
            JOptionPane.showMessageDialog(this, "Your information is valid.");
            db.addLogin(user, password);
            MainMenu mm = new MainMenu();
            mm.setVisible(true);
            this.dispose();
        }
        else{
            lblUsernameValidity.setForeground(Color.red);
            lblUsernameValidity.setText("INVALID");
            txtUsernameSignIn.setBackground(Color.red);
            lblPasswordValidity.setForeground(Color.red);
            lblPasswordValidity.setText("INVALID");
            pwfPasswordSignIn.setBackground(Color.red);
            lblUserValidity.setForeground(Color.red);
            lblUserValidity.setText("INVALID");
            cmboUserType.setBackground(Color.red);
        }
        
        
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnHelpSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpSignInActionPerformed
        HelpSignIn hsi = new HelpSignIn();
        hsi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHelpSignInActionPerformed

    private void txtUsernameSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameSignInMouseClicked
        txtUsernameSignIn.setText(null);
    }//GEN-LAST:event_txtUsernameSignInMouseClicked

    private void pwfPasswordSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwfPasswordSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwfPasswordSignInActionPerformed

    private void pwfPasswordSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwfPasswordSignInMouseClicked

    }//GEN-LAST:event_pwfPasswordSignInMouseClicked

    private void btnCancelSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSignInActionPerformed
        txtUsernameSignIn.setText(null);
        pwfPasswordSignIn.setText(null);
        lblUsernameValidity.setText(null);
        lblPasswordValidity.setText(null);
        txtUsernameSignIn.setBackground(Color.white);
        pwfPasswordSignIn.setBackground(Color.white);
    }//GEN-LAST:event_btnCancelSignInActionPerformed

    private void txtUsernameSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameSignInActionPerformed

    private void btnSignUpSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpSignInActionPerformed
        SignUp sip = new SignUp();
        sip.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnSignUpSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelSignIn;
    private javax.swing.JButton btnHelpSignIn;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUpSignIn;
    private javax.swing.JComboBox cmboUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCompanyNameSignIn;
    private javax.swing.JLabel lblPasswordSignIn;
    private javax.swing.JLabel lblPasswordValidity;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblUserValidity;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsernameValidity;
    private javax.swing.JPasswordField pwfPasswordSignIn;
    private java.awt.TextField txtUsernameSignIn;
    // End of variables declaration//GEN-END:variables
}
