import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author victorg
 */
public class StockManagement extends javax.swing.JFrame {

    DefaultTableModel dm;
    
    
    public StockManagement() {
        initComponents();
        DatabaseConnection db = new DatabaseConnection();
        ResultSet rs = db.displayStock();
        tblStockManagement.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
    
    private void filter(String qry){
        dm = (DefaultTableModel) tblStockManagement.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
        tblStockManagement.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(qry));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyNameStock = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStockManagement = new javax.swing.JTable();
        btnStockMainMenu = new javax.swing.JButton();
        btnStockHelp = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnRemoveProduct = new javax.swing.JButton();
        btnUpdateStockCount = new javax.swing.JButton();
        btnPriceList = new javax.swing.JButton();
        btnASC = new javax.swing.JButton();
        btnDESC = new javax.swing.JButton();
        btnAlphabetical = new javax.swing.JButton();
        btnNumberASC = new javax.swing.JButton();
        btnNumberDESC = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNameStock.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNameStock.setText("OBIJENCY FOOD STUFF");

        tblStockManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ProductID", "Product Name", "ProductType", "Product Count", "PriceID", "BARCODE"
            }
        ));
        jScrollPane1.setViewportView(tblStockManagement);

        btnStockMainMenu.setText("MAIN MENU");
        btnStockMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockMainMenuActionPerformed(evt);
            }
        });

        btnStockHelp.setText("HELP");
        btnStockHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockHelpActionPerformed(evt);
            }
        });

        btnAddProduct.setText("ADD PRODUCT");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnRemoveProduct.setText("REMOVE PRODUCT");
        btnRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductActionPerformed(evt);
            }
        });

        btnUpdateStockCount.setText("UPDATE STOCK COUNT");
        btnUpdateStockCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStockCountActionPerformed(evt);
            }
        });

        btnPriceList.setText("STOCK PRICE LIST");
        btnPriceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceListActionPerformed(evt);
            }
        });

        btnASC.setText("ASCENDING ORDER");
        btnASC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnASCActionPerformed(evt);
            }
        });

        btnDESC.setText("DESCENDING ORDER");
        btnDESC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDESCActionPerformed(evt);
            }
        });

        btnAlphabetical.setText("ALPHABETICAL");
        btnAlphabetical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlphabeticalActionPerformed(evt);
            }
        });

        btnNumberASC.setText("STOCK COUNT ASC");
        btnNumberASC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberASCActionPerformed(evt);
            }
        });

        btnNumberDESC.setText("STOCK COUNT DESC");
        btnNumberDESC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberDESCActionPerformed(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnNumberDESC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnASC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDESC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlphabetical, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNumberASC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStockMainMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblCompanyNameStock))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPriceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStockHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateStockCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCompanyNameStock, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddProduct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveProduct)
                                .addGap(12, 12, 12)
                                .addComponent(btnUpdateStockCount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPriceList))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnASC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDESC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlphabetical)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNumberASC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNumberDESC)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStockMainMenu)
                            .addComponent(btnStockHelp))))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    private void btnUpdateStockCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStockCountActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        int pID = Integer.parseInt(JOptionPane.showInputDialog(lblCompanyNameStock,"Please enter the product ID"));
        int add = Integer.parseInt(JOptionPane.showInputDialog(lblCompanyNameStock, "Enter the amount of stock you want to add."));
        int row = dc.updateStockCount(pID, add);
        if(row > 0){
            JOptionPane.showMessageDialog(this, "The stock count has been updated");
        }
        else{
            JOptionPane.showMessageDialog(this, "The stock count has been updated");
        }
    }//GEN-LAST:event_btnUpdateStockCountActionPerformed

    private void btnPriceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceListActionPerformed
        PriceList pl = new PriceList();
        pl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPriceListActionPerformed

    private void btnASCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnASCActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        ResultSet rs = dc.asc();
        tblStockManagement.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnASCActionPerformed

    private void btnStockMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockMainMenuActionPerformed
        MainMenu sm = new MainMenu();
        sm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStockMainMenuActionPerformed

    private void btnNumberDESCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberDESCActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        ResultSet rs = dc.countDesc();
        tblStockManagement.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnNumberDESCActionPerformed

    private void btnStockHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockHelpActionPerformed
        HelpStockManagement sm = new HelpStockManagement();
        sm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStockHelpActionPerformed

    private void btnDESCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDESCActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        ResultSet rs = dc.desc();
        tblStockManagement.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnDESCActionPerformed

    private void btnAlphabeticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlphabeticalActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        ResultSet rs = dc.alphabetical();
        tblStockManagement.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnAlphabeticalActionPerformed

    private void btnNumberASCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberASCActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        ResultSet rs = dc.countAsc();
        tblStockManagement.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnNumberASCActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        String pName = JOptionPane.showInputDialog(this, "Enter the name of the product");
        String[] types = {"Detergent", "Spices", "Hair", "Repellent", "Pain Relief",
        "Cooking", "Snacks", "Sweets", "Beverage", "Hygiene", "Celullar", "Cosmetic"};
         int x = JOptionPane.showOptionDialog(this, "Please select the category of the product",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, types, types[0]);
        String type = types[x];
        int pCount = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter the number of stock for the product"));
        String barcode = JOptionPane.showInputDialog(this, "Enter the barcode for the product");
        double price = Double.parseDouble(JOptionPane.showInputDialog(this, "Enter the price of the product"));
        double cPrice = Double.parseDouble(JOptionPane.showInputDialog(this, "Enter the cost-price of the product"));
        int row = dc.addProduct(pName, type, pCount, barcode, price, cPrice);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "The product has been added");
        }
        else{
            JOptionPane.showMessageDialog(this, "The product has not been added");
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        
        int change = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter the product ID of the product"));
        int row = dc.removeProduct(change);
        if (row > 0) {
            JOptionPane.showMessageDialog(this, "The product has been removed");
        }
        else{
            JOptionPane.showMessageDialog(this, "The product has not been removed");
        }
    }//GEN-LAST:event_btnRemoveProductActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String qry = txtSearch.getText().toLowerCase();
        filter(qry);
    }//GEN-LAST:event_txtSearchKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManagement().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnASC;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAlphabetical;
    private javax.swing.JButton btnDESC;
    private javax.swing.JButton btnNumberASC;
    private javax.swing.JButton btnNumberDESC;
    private javax.swing.JButton btnPriceList;
    private javax.swing.JButton btnRemoveProduct;
    private javax.swing.JButton btnStockHelp;
    private javax.swing.JButton btnStockMainMenu;
    private javax.swing.JButton btnUpdateStockCount;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompanyNameStock;
    private javax.swing.JTable tblStockManagement;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
}
