import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author victorg
 */
public class UsersTable extends javax.swing.JFrame {

    /**
     * Creates new form UsersTable
     */
    public UsersTable() {
        initComponents();
        DatabaseConnection db = new DatabaseConnection();
        ResultSet rs = db.displayUser();
        tblUsersTable.setModel(DbUtils.resultSetToTableModel(rs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyNameMainMenu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsersTable = new javax.swing.JTable();
        btnUsersTableMainMenu = new javax.swing.JButton();
        lblHeadingUserTable = new javax.swing.JLabel();
        btnUserTableHelp = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompanyNameMainMenu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCompanyNameMainMenu.setText("OBIJENCY FOOD STUFF");

        tblUsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Name", "Surname", "Status", "Date Of Birth", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblUsersTable);

        btnUsersTableMainMenu.setText("BACK TO MAIN MENU");
        btnUsersTableMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersTableMainMenuActionPerformed(evt);
            }
        });

        lblHeadingUserTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHeadingUserTable.setText("OBIJENCY FOOD STUFF SYSTEM USERS");

        btnUserTableHelp.setText("HELP");
        btnUserTableHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserTableHelpActionPerformed(evt);
            }
        });

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(lblCompanyNameMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(lblHeadingUserTable, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnUsersTableMainMenu)
                .addGap(177, 177, 177)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUserTableHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCompanyNameMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblHeadingUserTable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsersTableMainMenu)
                    .addComponent(btnUserTableHelp)
                    .addComponent(btnEdit))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersTableMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersTableMainMenuActionPerformed
        MainMenu ut = new MainMenu();
        ut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsersTableMainMenuActionPerformed

    private void btnUserTableHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserTableHelpActionPerformed
        HelpUserTable us = new HelpUserTable();
        us.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserTableHelpActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        int uID = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter the user ID of the person."));
        String[] choices = {"Name", "Surname", "Status", "Username", "Password"};
        int x = JOptionPane.showOptionDialog(this, "Please select the category of the product",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, choices, choices[0]);
        String choice = choices[x];
        String newVal = (JOptionPane.showInputDialog(this, "Enter the new "
                + choice + " for the user"));
        int row = dc.editUserTable(uID, choice, newVal);
        if(row > 0){
            JOptionPane.showMessageDialog(this, "The " + choice + " has been updated");
        }
        else{
            JOptionPane.showMessageDialog(this, "The " + choice + " has not been updated");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnUserTableHelp;
    private javax.swing.JButton btnUsersTableMainMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompanyNameMainMenu;
    private javax.swing.JLabel lblHeadingUserTable;
    private javax.swing.JTable tblUsersTable;
    // End of variables declaration//GEN-END:variables
}
